#!/bin/bash

# Script to prepare deployment commands for Gozain with GCS

PROJECT_ID="gozain-suite-iso27001"
SERVICE_NAME="gozain"
REGION="us-central1"
IMAGE_NAME="gcr.io/${PROJECT_ID}/${SERVICE_NAME}"

echo "==================================="
echo "🚀 DEPLOYMENT COMMANDS FOR GOZAIN"
echo "==================================="
echo ""
echo "Please run these commands in your terminal:"
echo ""
echo "1. First, authenticate and set project:"
echo "   gcloud auth login"
echo "   gcloud config set project ${PROJECT_ID}"
echo ""
echo "2. Build and push Docker image:"
echo "   docker build -t ${IMAGE_NAME}:latest ."
echo "   docker push ${IMAGE_NAME}:latest"
echo ""
echo "3. Deploy to Cloud Run:"
echo "   gcloud run deploy ${SERVICE_NAME} \\"
echo "     --image ${IMAGE_NAME}:latest \\"
echo "     --platform managed \\"
echo "     --region ${REGION} \\"
echo "     --allow-unauthenticated \\"
echo "     --set-env-vars \"USE_GCS=true,GCS_BUCKET_NAME=inventario-iso27001-data\" \\"
echo "     --project ${PROJECT_ID}"
echo ""
echo "4. After deployment, test the GCS connection:"
echo "   curl https://${SERVICE_NAME}-687354193398.us-central1.run.app/api/debug/gcs"
echo ""
echo "5. Access the application:"
echo "   https://${SERVICE_NAME}-687354193398.us-central1.run.app"
echo ""
echo "==================================="