name: Cypress E2E Tests

on:
  workflow_dispatch:

env:
  CYPRESS_BASE_URL: https://gozain-687354193398.us-central1.run.app

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Wait for deployment (if triggered by push)
      if: github.event_name == 'push'
      run: |
        echo "Waiting for deployment to complete..."
        sleep 60
    
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: ${{ matrix.browser }}
        config: baseUrl=${{ env.CYPRESS_BASE_URL }}
        record: false
        spec: |
          cypress/e2e/01-organization-management.cy.js
          cypress/e2e/02-inventory-module.cy.js
          cypress/e2e/03-navigation.cy.js
          cypress/e2e/04-impacts-module.cy.js
          cypress/e2e/11-maturity-simple-test.cy.js
          cypress/e2e/13-maturity-navigation-final-check.cy.js
          cypress/e2e/14-business-processes-personal.cy.js
          cypress/e2e/15-business-processes-projects.cy.js
          cypress/e2e/16-business-processes-infrastructure.cy.js
          cypress/e2e/17-business-processes-security.cy.js
          cypress/e2e/18-business-processes-crisis.cy.js
    
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots-${{ matrix.browser }}
        path: cypress/screenshots
        retention-days: 7
    
    - name: Upload videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos-${{ matrix.browser }}
        path: cypress/videos
        retention-days: 7