name: Cypress E2E Tests Optimized

on:
  push:
    branches: [ refactor/inventario-dashboard-lista ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CYPRESS_BASE_URL: http://localhost:8080
  CYPRESS_defaultCommandTimeout: 10000
  CYPRESS_video: false
  CYPRESS_screenshotOnRunFailure: false

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Node dependencies
      run: npm ci
    
    - name: Start application
      run: |
        python app.py &
        sleep 5
        curl -f http://localhost:8080 || exit 1
      env:
        PORT: 8080
    
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        config: baseUrl=${{ env.CYPRESS_BASE_URL }}
        record: false
        spec: |
          cypress/e2e/00-setup.cy.js
          cypress/e2e/00-test-setup-optimized.cy.js
          cypress/e2e/01-navigation.cy.js
          cypress/e2e/02-inventory.cy.js
          cypress/e2e/03-impacts-optimized.cy.js
    
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        retention-days: 7