name: Test E2E Local with Act

on:
  workflow_dispatch:
  push:
    branches: [ test-act ]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          libgtk2.0-0 \
          libgtk-3-0 \
          libgbm-dev \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          libxtst6 \
          xauth \
          xvfb

    - name: Install dependencies
      run: |
        npm ci
        npx cypress install
        npx cypress verify

    - name: Run Cypress tests against production
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
        ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'
      run: |
        echo "🧪 Running E2E tests against production..."
        # Ejecutar con xvfb-run para proporcionar display virtual
        xvfb-run -a --server-args="-screen 0 1920x1080x24" \
          npx cypress run \
          --spec "cypress/e2e/00-setup.cy.js,cypress/e2e/01-navigation.cy.js,cypress/e2e/02-inventory.cy.js" \
          --config "defaultCommandTimeout=30000,pageLoadTimeout=60000,viewportWidth=1920,viewportHeight=1080" \
          --browser electron \
          --headed \
          || true
        
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: cypress/screenshots