name: Test Simple Fix para Act

on:
  workflow_dispatch:

jobs:
  test-visibility:
    runs-on: ubuntu-latest
    container: cypress/included:13.17.0
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Test del problema de visibilidad
      run: |
        echo "游댌 Test directo del problema..."
        
        # No necesitamos instalar nada, cypress ya est치 incluido
        
        # Ejecutar test espec칤fico
        CYPRESS_BASE_URL=https://gozain-h556ekexqa-uc.a.run.app \
        CI=true \
        cypress run \
          --spec "cypress/e2e/02-inventory.cy.js" \
          --config "defaultCommandTimeout=15000,video=false" \
          --browser chrome \
          --headed || true
          
        echo "游늵 Resultado del test"
        
    - name: Test con soluci칩n jQuery
      run: |
        echo "游댢 Probando soluci칩n con jQuery..."
        
        # Crear test con soluci칩n
        cat > cypress/e2e/99-jquery-fix.cy.js << 'EOF'
        describe('Fix con jQuery', () => {
          it('Cambiar vista con jQuery directo', () => {
            cy.loginWithOrg('E2E Test Organization')
            cy.get('.tool-card').contains('Inventario de Activos').click()
            cy.wait(2000)
            
            // En lugar de usar switchView, manipular DOM directamente
            cy.window().then(win => {
              // Forzar cambio de vista con jQuery
              win.$('#dashboardView').hide()
              win.$('#listaView').show()
              
              // Disparar eventos para que la app lo detecte
              win.$('#btnVistaLista').trigger('click')
            })
            
            cy.wait(1000)
            
            // Ahora verificar que funciona
            cy.get('#tablaActivos').should('exist')
            cy.get('#btnNuevoActivo').should('exist')
          })
        })
        EOF
        
        CYPRESS_BASE_URL=https://gozain-h556ekexqa-uc.a.run.app \
        CI=true \
        cypress run \
          --spec "cypress/e2e/99-jquery-fix.cy.js" \
          --browser chrome