name: Full E2E Test with Act

on:
  workflow_dispatch:
  push:
    branches:
      - fix/cypress-view-switching-classes

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Cypress dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2 \
            libxtst6 \
            xauth \
            xvfb
      
      - name: Install Cypress
        run: |
          npm ci
          npx cypress install
          npx cypress verify
      
      - name: Start application server
        run: |
          export USE_LOCAL_STORAGE=true
          cd backend
          python app.py &
          echo $! > server.pid
          # Wait for server to be ready
          for i in {1..30}; do
            if curl -f http://localhost:8080/ > /dev/null 2>&1; then
              echo "Server is ready!"
              break
            fi
            echo "Waiting for server... attempt $i"
            sleep 2
          done
      
      - name: Run Cypress tests
        run: |
          xvfb-run -a npx cypress run --spec "cypress/e2e/00-setup.cy.js,cypress/e2e/01-navigation.cy.js,cypress/e2e/02-inventory.cy.js"
        env:
          CYPRESS_baseUrl: http://localhost:8080
      
      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
          fi
          
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7