name: Test E2E with Act (Cypress Image)

on:
  workflow_dispatch:
  push:
    branches: [ test-act-cypress ]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.17.0
      options: --user root
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Cypress
      run: |
        cypress verify
        cypress info

    - name: Run Cypress tests - Setup
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
      run: |
        echo "🧪 Test 1: Setup test"
        npx cypress run \
          --spec "cypress/e2e/00-setup.cy.js" \
          --config "defaultCommandTimeout=30000" \
          --browser chrome

    - name: Run Cypress tests - Navigation
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
      continue-on-error: true
      run: |
        echo "🧪 Test 2: Navigation test"
        npx cypress run \
          --spec "cypress/e2e/01-navigation.cy.js" \
          --config "defaultCommandTimeout=30000" \
          --browser chrome

    - name: Run Cypress tests - Inventory with fixes
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
      continue-on-error: true
      run: |
        echo "🧪 Test 3: Inventory test (problemático)"
        npx cypress run \
          --spec "cypress/e2e/02-inventory.cy.js" \
          --config "defaultCommandTimeout=40000,pageLoadTimeout=60000" \
          --browser chrome
          
    - name: Summary
      if: always()
      run: |
        echo "📊 Resumen de tests"
        echo "=================="
        ls -la cypress/screenshots/ 2>/dev/null || echo "No screenshots"
        ls -la cypress/videos/ 2>/dev/null || echo "No videos"