name: Test Act with Electron

on:
  workflow_dispatch:

jobs:
  cypress-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.17.0
      options: --user root
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Cypress with Electron (no Xvfb needed)
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
      run: |
        echo "🎯 Running Cypress with Electron to avoid Xvfb issues..."
        
        # Electron runs headless by default and doesn't need Xvfb
        cypress run \
          --spec "cypress/e2e/02-inventory.cy.js" \
          --browser electron \
          --config "video=false" \
          --headless
          
    - name: Test jQuery fix with Electron
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
      run: |
        echo "🔧 Testing jQuery fix..."
        
        # Copy our jQuery fix test
        cp claude_tools/test_jquery_fix.js cypress/e2e/99-jquery-fix.cy.js
        
        # Run with Electron
        cypress run \
          --spec "cypress/e2e/99-jquery-fix.cy.js" \
          --browser electron \
          --headless