name: Simple Test Against Gozain Production

on:
  workflow_dispatch:
  push:
    branches:
      - fix/cypress-view-switching-classes

jobs:
  test-prod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Cypress Docker against production
        run: |
          docker run --rm \
            -v $PWD:/e2e \
            -w /e2e \
            -e CYPRESS_baseUrl=https://gozain-687354193398.us-central1.run.app \
            cypress/included:13.17.0 \
            --spec "cypress/e2e/00-setup.cy.js,cypress/e2e/01-navigation.cy.js,cypress/e2e/02-inventory.cy.js"