name: Minimal Act Test

on:
  workflow_dispatch:

jobs:
  minimal-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.17.0
      options: --user root
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run single test with jQuery fix
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
      run: |
        echo "🧪 Testing jQuery fix approach..."
        
        # Create a minimal test that uses jQuery directly
        cat > cypress/e2e/99-minimal-jquery.cy.js << 'EOF'
        describe('Minimal jQuery Test', () => {
          it('Cambiar vista con jQuery', () => {
            // Login
            cy.visit('/')
            cy.get('#organizations').select('E2E Test Organization')
            cy.contains('button', 'Entrar').click()
            
            // Navigate to inventory
            cy.get('.tool-card').contains('Inventario de Activos').click()
            cy.wait(2000)
            
            // Use jQuery directly instead of switchView
            cy.window().then(win => {
              // Force view change with jQuery
              win.$('#dashboardView').hide()
              win.$('#listaView').show()
              win.$('#btnVistaDashboard').removeClass('active')
              win.$('#btnVistaLista').addClass('active')
            })
            
            // Verify it worked
            cy.get('#tablaActivos').should('be.visible')
            cy.get('#btnNuevoActivo').should('be.visible')
            
            // Test creating an asset
            cy.get('#btnNuevoActivo').click()
            cy.get('#modalActivo').should('be.visible')
            cy.get('#tipoActivo').select('Hardware')
            cy.get('#nombreActivo').type('Test Hardware jQuery')
            cy.get('#btnGuardarActivo').click()
            
            // Verify asset was created
            cy.get('#tablaActivos').should('contain', 'Test Hardware jQuery')
          })
        })
        EOF
        
        # Run the test with electron
        cypress run \
          --spec "cypress/e2e/99-minimal-jquery.cy.js" \
          --browser electron \
          --config "video=false,defaultCommandTimeout=15000" \
          --headless