name: Act Test with Base Image

on:
  workflow_dispatch:

jobs:
  test-base:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        # Install xvfb and other dependencies
        apt-get update
        apt-get install -y xvfb libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth dbus-x11
        
        # Install Cypress
        npm install cypress@13.17.0 --no-save
        
    - name: Run test with jQuery fix
      env:
        CYPRESS_BASE_URL: https://gozain-h556ekexqa-uc.a.run.app
        CI: true
      run: |
        echo "🧪 Running jQuery fix test..."
        
        # Create test file
        cat > cypress/e2e/99-jquery-base.cy.js << 'EOF'
        describe('jQuery Base Test', () => {
          it('Vista lista con jQuery', () => {
            cy.loginWithOrg('E2E Test Organization')
            cy.get('.tool-card').contains('Inventario de Activos').click()
            cy.wait(2000)
            
            // jQuery fix
            cy.window().then(win => {
              win.$('#dashboardView').hide()
              win.$('#listaView').show() 
              win.$('#btnVistaLista').addClass('active')
              win.$('#btnVistaDashboard').removeClass('active')
            })
            
            // Verify
            cy.get('#tablaActivos').should('exist')
            cy.get('#btnNuevoActivo').should('exist').click()
            cy.get('#modalActivo').should('be.visible')
            cy.get('#btnCancelarActivo').click()
          })
        })
        EOF
        
        # Run with xvfb-run to handle X11
        xvfb-run -a npx cypress run \
          --spec "cypress/e2e/99-jquery-base.cy.js" \
          --browser electron \
          --config "video=false"