name: Test CSS Fix with Act

on:
  workflow_dispatch:
  push:
    branches:
      - fix/cypress-view-switching-classes

jobs:
  cypress-css-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.17.0
      options: --user 1001
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Show environment info
        run: |
          echo "Container user: $(whoami)"
          echo "User ID: $(id -u)"
          echo "Group ID: $(id -g)"
          echo "Working directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          npx cypress --version
      
      - name: Install dependencies
        run: |
          cd apps/inventario
          npm ci
      
      - name: Run Cypress tests
        run: |
          cd apps/inventario
          # Run with xvfb-run to provide display
          xvfb-run -a npx cypress run --spec "cypress/e2e/setup.cy.js,cypress/e2e/navigation.cy.js,cypress/e2e/inventory.cy.js"
        env:
          CYPRESS_baseUrl: http://localhost:8080
          
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/inventario/cypress/screenshots
          retention-days: 7