name: Test E2E Simple for Act

on:
  workflow_dispatch:
  push:
    branches: [ test-act-simple ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/included:13.17.0
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Test Setup
      run: |
        echo "🧪 Running setup test..."
        cypress run \
          --spec "cypress/e2e/00-setup.cy.js" \
          --config baseUrl=https://gozain-h556ekexqa-uc.a.run.app \
          --browser chrome \
          --quiet

    - name: Test Navigation
      continue-on-error: true
      run: |
        echo "🧪 Running navigation test..."
        cypress run \
          --spec "cypress/e2e/01-navigation.cy.js" \
          --config baseUrl=https://gozain-h556ekexqa-uc.a.run.app,defaultCommandTimeout=30000 \
          --browser chrome

    - name: Test Inventory
      continue-on-error: true
      run: |
        echo "🧪 Running inventory test (with visibility issues)..."
        CI=true cypress run \
          --spec "cypress/e2e/02-inventory.cy.js" \
          --config baseUrl=https://gozain-h556ekexqa-uc.a.run.app,defaultCommandTimeout=40000,pageLoadTimeout=60000 \
          --browser chrome