name: Test with Cypress Container

on:
  workflow_dispatch:
  push:
    branches:
      - fix/cypress-view-switching-classes

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.17.0
      options: --user 1001
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Cypress tests against production
        run: |
          cypress run --spec "cypress/e2e/00-setup.cy.js,cypress/e2e/01-navigation.cy.js,cypress/e2e/02-inventory.cy.js"
        env:
          CYPRESS_baseUrl: https://gozain-687354193398.us-central1.run.app