name: Test Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test secret exists
        run: |
          if [ -n "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "✅ GCP_SA_KEY secret is configured"
          else
            echo "❌ GCP_SA_KEY secret is missing"
            exit 1
          fi
      
      - name: Show environment
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Repo: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"